# Generated by Django 5.2.9 on 2025-12-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ekipman Adı')),
                ('code', models.CharField(max_length=50, verbose_name='Ekipman Kodu')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokasyon')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Üretici')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seri No')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Satın Alma Tarihi')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Garanti Bitiş')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('maintenance', 'Bakımda'), ('broken', 'Arızalı')], default='active', max_length=20, verbose_name='Durum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='plants.plant', verbose_name='Tesis')),
            ],
            options={
                'verbose_name': 'Ekipman',
                'verbose_name_plural': 'Ekipmanlar',
                'ordering': ['plant', 'name'],
                'unique_together': {('plant', 'code')},
            },
        ),
    ]
